<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>PostNL10x15.VirtualPrinter</AssemblyName>
    <RootNamespace>PostNL10x15.VirtualPrinter</RootNamespace>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
    <CsWinRTComponent>true</CsWinRTComponent>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x64</Platforms>
    <SelfContained>false</SelfContained>
    <PublishSelfContained>false</PublishSelfContained>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <GenerateProgramFile>false</GenerateProgramFile>
    <Nullable>enable</Nullable>
    <SatelliteResourceLanguages>nl</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
  </ItemGroup>
</Project>
